services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: battle-realms-trainer:alpine
    container_name: battle-realms-trainer
    volumes:
      - ./:/app
    stdin_open: true
    tty: true
    restart: "no"
